def enum(**enums):
    return type('Enum', (), enums)

class Enums: 
    MapItems = enum(BLANK='BLANK', BOMB='BOMB', EXPLOSION='EXPLOSION', WALL='WALL', BLOCK='BLOCK', POWERUP='POWERUP')
    PlayerActions = enum(MOVEDOWN='MOVEDOWN', MOVEUP='MOVEUP', MOVELEFT='MOVELEFT', MOVERIGHT='MOVERIGHT', STAYPUT='STAYPUT', PLACEBOMB='PLACEBOMB', BOMBANDMOVELEFT='BOMBANDMOVELEFT', BOMBANDMOVERIGHT='BOMBANDMOVERIGHT', BOMBANDMOVEUP='BOMBANDMOVEUP', BOMBANDMOVEDOWN='BOMBANDMOVEDOWN')
    PowerUps = enum(FIREUP='FIREUP', BOMBUP='BOMBUP', NONE='NONE')

WALKABLE = [Enums.MapItems.BLANK, Enums.MapItems.POWERUP, Enums.MapItems.EXPLOSION]